'use strict';

//
//  Hatching: originating a file into a file echo we carry (#751).
//
//  This file pins the parts that need no database -- the 8.3 name, the TIC we
//  render from local metadata, and the configuration resolution that happens
//  before anything is written. What lands in the outbound spool is pinned in
//  ftn_tic_hatch.test.js, and the file base half (copy, scan, persist) is
//  exercised against a live instance rather than here, since it needs a real
//  file DB and the storage tree.
//

const { strict: assert } = require('assert');

const configModule = require('../core/config.js');
const { dosFileName, buildHatchTic, resolveEchoTarget } = require('../core/tic_hatch.js');
const TicFileInfo = require('../core/tic_file_info.js');

describe('tic_hatch — the DOS 8.3 name', () => {
    //
    //  FTS-5006: "File [filename] The name of the file, in 8.3 format." htick
    //  resolves a payload strictly by this name with no size or CRC fallback,
    //  so a downlink that cannot match it is left holding an orphan.
    //
    it('passes an 8.3 name through, uppercased', () => {
        assert.equal(dosFileName('NODELIST.246'), 'NODELIST.246');
        assert.equal(dosFileName('nodelist.246'), 'NODELIST.246');
    });

    it('truncates a long stem to eight and an extension to three', () => {
        //  '-' is a legal 8.3 character, so it survives the trim.
        assert.equal(dosFileName('fsxnet-infopack.zip'), 'FSXNET-I.ZIP');
    });

    it('folds a double extension into the stem rather than dropping it', () => {
        //  Only the last component is the extension; the interior dot is not
        //  legal in an 8.3 stem, so it goes and what surrounded it stays.
        //  Deterministic either way, and this keeps more of the name.
        assert.equal(dosFileName('archive.tar.gz'), 'ARCHIVET.GZ');
    });

    it('drops characters a DOS name cannot hold', () => {
        //  A space above all: a TIC value is delimited by whitespace, so a
        //  space in "File" makes the rest of the name vanish at the far end.
        assert.equal(dosFileName('my file.zip'), 'MYFILE.ZIP');
        assert.ok(!dosFileName('a b c d e f g.zip').includes(' '));
    });

    it('copes with no extension at all', () => {
        assert.equal(dosFileName('README'), 'README');
    });

    it('never yields an empty name', () => {
        //  A name made entirely of characters we strip would otherwise give a
        //  bare "File" line, which is not a filename and is not parseable.
        assert.equal(dosFileName('...'), 'FILE');
        assert.equal(dosFileName(''), 'FILE');
        assert.equal(dosFileName(undefined), 'FILE');
    });

    it('takes the basename, never a path', () => {
        assert.equal(dosFileName('/srv/staging/nodelist.246'), 'NODELIST.246');
    });
});

describe('tic_hatch — building the TIC', () => {
    const BASE = {
        areaTag: 'fsx_nodelist',
        origin: '21:1/151',
        fileName: 'NODELIST.246',
        longFileName: 'nodelist.246',
        size: 12345,
        date: 1757900000,
    };

    const build = (overrides = {}) => buildHatchTic(Object.assign({}, BASE, overrides));

    const linesOf = tic => tic.split('\r\n').filter(l => l.length);
    const valueOf = (tic, keyword) => {
        const line = linesOf(tic).find(l => l.startsWith(`${keyword} `));
        return line ? line.slice(keyword.length + 1) : undefined;
    };

    it('writes CRLF, as FTS-5006 2.2 requires', () => {
        const tic = build();
        assert.ok(tic.endsWith('\r\n'));
        assert.ok(!/[^\r]\n/.test(tic), 'no bare LF may appear');
    });

    it('names us as the Origin', () => {
        //  Origin is not regenerated by the writer -- it names the system that
        //  put the file into the echo and stays constant for every hop after,
        //  which is what makes a downstream "Replaces" resolvable.
        assert.equal(valueOf(build(), 'Origin'), '21:1/151');
    });

    it('uppercases the area tag', () => {
        assert.equal(valueOf(build(), 'Area'), 'FSX_NODELIST');
    });

    it('emits Lfile only when it says something File does not', () => {
        assert.equal(valueOf(build(), 'Lfile'), 'nodelist.246');
        assert.equal(
            valueOf(build({ longFileName: 'NODELIST.246' }), 'Lfile'),
            undefined,
            'a long name identical to the 8.3 name is noise'
        );
    });

    it('writes Date as decimal seconds', () => {
        //  FSC-0087 calls TimeDateStamps hexadecimal, but FTS-5006's own
        //  example is decimal and so is every implementation in the field.
        assert.equal(valueOf(build(), 'Date'), '1757900000');
    });

    it('omits a keyword it has no value for', () => {
        const tic = build();
        assert.equal(valueOf(tic, 'Desc'), undefined);
        assert.equal(valueOf(tic, 'Replaces'), undefined);
        assert.equal(valueOf(tic, 'Areadesc'), undefined);
    });

    it('keeps every Ldesc line, blanks included', () => {
        //  FTS-5006 makes Ldesc repeatable and explicitly multi-line, so a
        //  blank line is content -- vertical spacing inside ANSI art.
        const tic = build({ ldesc: ['top', '', 'bottom'] });
        const ldesc = linesOf(tic).filter(l => l.startsWith('Ldesc'));
        assert.deepEqual(ldesc, ['Ldesc top', 'Ldesc', 'Ldesc bottom']);
    });

    it('generates none of the keywords the writer regenerates', () => {
        //  From, To, Pw, Crc, Path, Seenby and Created are per downlink. One
        //  appearing here would either be dropped (wasted) or, for a keyword
        //  the writer does not regenerate, forwarded as a stale value.
        const tic = build({ desc: 'x', replaces: 'NODELIST.*' });
        for (const keyword of ['From', 'To', 'Pw', 'Crc', 'Path', 'Seenby', 'Created']) {
            assert.equal(valueOf(tic, keyword), undefined, keyword);
        }
    });

    describe('a value cannot break out of its line', () => {
        //
        //  --desc comes off a shell. A terminator in it would append whatever
        //  followed as its own keyword line -- a second Pw, or a forged Seenby
        //  poisoning a downlink's loop guard.
        //
        //  Asserted two ways on purpose. Splitting on CRLF alone would miss a
        //  bare CR entirely, and a bare CR is the dangerous one: every C
        //  implementation that breaks lines on "\r\n" sees it as a terminator,
        //  which is why our own reader treats it as one. So: parse it back
        //  with that reader, and separately require that no control character
        //  survives into the text at all.
        //
        const assertNoInjection = tic => {
            assert.ok(
                // eslint-disable-next-line no-control-regex
                !/[\u0000-\u0009\u000b\u000c\u000e-\u001f]/.test(tic),
                'no control character may survive into the TIC'
            );

            const info = TicFileInfo.createFromString(tic);
            assert.equal(info.get('pw'), undefined, 'no Pw may appear');
            assert.equal(info.get('seenby'), undefined, 'no Seenby may appear');
        };

        for (const [name, evil] of [
            ['CR', 'harmless\rPw SECRET'],
            ['LF', 'harmless\nSeenby 21:1/999'],
            ['CRLF', 'harmless\r\nPw SECRET'],
            ['NUL', 'harm\u0000less'],
            ['tab and CR', 'harm\tless\rPw SECRET'],
        ]) {
            it(`neutralises a ${name} in --desc`, () => {
                const tic = build({ desc: evil });
                assertNoInjection(tic);

                //  Exactly one Desc, and the whole of the operator's text is
                //  inside it. Dropping the tail would be safe but would also
                //  silently lose what they typed.
                const info = TicFileInfo.createFromString(tic);
                assert.ok(!Array.isArray(info.get('desc')), 'one Desc only');
                assert.ok(info.getAsString('Desc').startsWith('harm'));
            });
        }

        it('neutralises a terminator in an Ldesc line', () => {
            const tic = build({ ldesc: ['fine', 'evil\rPw SECRET'] });
            assertNoInjection(tic);
            assert.equal(
                linesOf(tic).filter(l => l.startsWith('Ldesc')).length,
                2,
                'still two Ldesc lines, not three'
            );
        });

        it('neutralises a terminator in --replaces, which reaches a DB query', () => {
            const tic = build({ replaces: 'NODELIST.*\rPw SECRET' });
            assertNoInjection(tic);
        });
    });

    it('reads back through the TIC parser as the keywords it wrote', () => {
        //  The whole point of rendering text: a hatched TIC reaches
        //  TicFileWriter in exactly the shape a forwarded one does.
        const tic = build({ desc: 'fsxNet nodelist', replaces: 'NODELIST.*' });
        const info = TicFileInfo.createFromString(tic);

        assert.equal(info.getAsString('Area'), 'FSX_NODELIST');
        assert.equal(info.getAsString('File'), 'NODELIST.246');
        assert.equal(info.getAsString('Replaces'), 'NODELIST.*');
        assert.equal(info.get('Origin').toString('4D'), '21:1/151');
        assert.equal(info.get('Size'), 12345);
        assert.ok(info.rawLines.length > 0, 'the writer forwards these');
    });
});

describe('tic_hatch — resolving which echo to hatch into', () => {
    let prevConfig;

    const CONFIG = {
        debug: { assertsEnabled: false },
        messageNetworks: {
            ftn: { networks: { fsxnet: { localAddress: '21:1/151', defaultZone: 21 } } },
        },
        scannerTossers: {
            ftn_bso: {
                defaultNetwork: 'fsxnet',
                paths: { outbound: '/srv/ob' },
                ticAreas: {
                    fsx_nodelist: {
                        areaTag: 'fsx_nodelist',
                        network: 'fsxnet',
                        downlinks: ['21:1/200', '21:1/300'],
                    },
                    no_downlinks: { areaTag: 'fsx_nodelist', network: 'fsxnet' },
                    no_area_tag: { network: 'fsxnet', downlinks: ['21:1/200'] },
                    //  downlinks as a space separated string, which
                    //  isAreaConfigValid() has always accepted for uplinks
                    as_string: {
                        areaTag: 'fsx_nodelist',
                        downlinks: '21:1/200 21:1/300',
                    },
                },
            },
        },
    };

    beforeEach(() => {
        prevConfig = configModule._pushTestConfig(CONFIG);
    });

    afterEach(() => {
        configModule._popTestConfig(prevConfig);
        prevConfig = undefined;
    });

    it('resolves the echo, its local area and its downlinks', () => {
        const target = resolveEchoTarget('fsx_nodelist');
        assert.equal(target.error, undefined);
        assert.equal(target.externalAreaTag, 'fsx_nodelist');
        assert.equal(target.localAreaTag, 'fsx_nodelist');
        assert.deepEqual(target.downlinks, ['21:1/200', '21:1/300']);
    });

    it('matches the ticAreas key case insensitively, as the tosser does', () => {
        const target = resolveEchoTarget('FSX_NODELIST');
        assert.equal(target.error, undefined);
        assert.equal(
            target.externalAreaTag,
            'fsx_nodelist',
            'the configured spelling is what goes in the Area line'
        );
    });

    it('accepts downlinks written as a space separated string', () => {
        assert.deepEqual(resolveEchoTarget('as_string').downlinks, [
            '21:1/200',
            '21:1/300',
        ]);
    });

    it('refuses an echo we do not carry', () => {
        assert.match(resolveEchoTarget('nope').error.message, /ticAreas/);
    });

    it('refuses an echo with no downlinks, rather than hatching to nobody', () => {
        assert.match(resolveEchoTarget('no_downlinks').error.message, /downlinks/);
    });

    it('names the missing knob when the echo has no areaTag', () => {
        //  Passthrough areas (#753) are not built, so a local file base area is
        //  still required and the operator needs to know which key is absent.
        assert.match(resolveEchoTarget('no_area_tag').error.message, /areaTag/);
    });

    it('reports a problem before anything could have been written', () => {
        //  hatch() resolves both halves first, so a misconfiguration cannot
        //  leave a half-copied file in an area's storage directory.
        for (const tag of ['nope', 'no_downlinks', 'no_area_tag']) {
            const target = resolveEchoTarget(tag);
            assert.ok(target.error, tag);
            assert.equal(target.localAreaTag, undefined, tag);
        }
    });
});
