/* jslint node: true */
'use strict';

//  ENiGMA½
const { NodeType } = require('./schema.js');

//  deps
const paths = require('path');

//
//  Projects the internal configuration schema into a JSON Schema document
//  (draft 2020-12).
//
//  The schema this reads is derived from core/config_default.js and annotated
//  by core/config/meta.js; see core/config/schema.js. Nothing new is decided
//  here. This module is a *projection*, not a second description -- if the
//  emitted document and the validator ever disagree about a configuration, the
//  bug is here.
//
//  That rule is why there is no key-pattern support for open maps, which the
//  design floated. The validator does not check the *format* of an open map's
//  keys, so emitting a "patternProperties" constraint would make the artifact
//  reject configurations ENiGMA itself accepts -- exactly the two-sources-of-
//  truth drift the whole effort exists to prevent. If key patterns are wanted,
//  they belong in the validator first, and this will follow for free.
//
//  Three things a consumer of the artifact has to know, all stated in the
//  emitted document itself:
//
//    * It describes the *resolved, merged* configuration. "@reference:",
//      "@environment:" and "@file:" specs are substituted before any of this
//      applies, so a raw config.hjson may legitimately carry a string where
//      this says "number".
//
//    * A configuration file may be a fragment: "includes" and the defaults
//      supply the rest. Hence nothing is ever "required".
//
//    * An unrecognised key is an *error* to a JSON Schema validator and only
//      a *warning* to ENiGMA, which boots regardless.
//
//  The output has to be byte-identical wherever it is generated, or the
//  staleness guard reports a difference between two checkouts as a stale
//  artifact. Roughly thirty defaults in config_default.js are built from
//  __dirname and so embed the installation directory; those are described
//  rather than quoted. See installDerived() below.
//

const JSON_SCHEMA_DRAFT = 'https://json-schema.org/draft/2020-12/schema';

const SCHEMA_ID =
    'https://raw.githubusercontent.com/NuSkooler/enigma-bbs/master/misc/config.schema.json';

//  What "a bare scalar is shorthand for this block" accepts
const SHORTHAND_TYPES = [NodeType.String, NodeType.Number, NodeType.Boolean];

const ROOT_COMMENT = [
    'Generated by "npm run build:schema" from core/config_default.js and',
    'core/config/meta.js. Do not edit by hand.',
    '',
    'Describes the resolved, merged configuration: "@reference:",',
    '"@environment:" and "@file:" specs are substituted before this applies, so',
    'an unresolved spec in a raw config.hjson may read as a type error here',
    'while being perfectly correct.',
    '',
    'Nothing is "required": every setting either has a default or is optional,',
    'and a configuration file may be a fragment completed by "includes".',
    '',
    'Where this says "additionalProperties": false, ENiGMA itself only warns.',
    'It never refuses to boot over a key it does not recognise.',
].join('\n');

//
//  Where this checkout happens to live. Nothing carrying it may reach the
//  artifact: a default of "/home/someone/enigma-bbs/misc/bad_passwords.txt"
//  is not a default of ENiGMA½, it is a property of one machine, and quoting
//  it would both mislead a consumer and make the file differ between the
//  developer who generated it and the CI that checks it.
//
const INSTALL_ROOT = paths.resolve(__dirname, '..', '..');

const posix = value => String(value).split(paths.sep).join('/');

function underInstallRoot(value) {
    if ('string' === typeof value) {
        return value.startsWith(INSTALL_ROOT + paths.sep);
    }
    if (Array.isArray(value)) {
        return value.some(underInstallRoot);
    }
    if (value && 'object' === typeof value) {
        return Object.values(value).some(underInstallRoot);
    }
    return false;
}

//
//  Say what the default is without quoting it. A consumer that wrote a
//  relative path back into config.hjson would be wrong -- the real value is
//  absolute -- so this deliberately goes in $comment rather than "default".
//
function installDerived(value) {
    if ('string' !== typeof value) {
        return 'Default is derived from the installation directory.';
    }

    const relative = posix(value.slice(INSTALL_ROOT.length + 1));
    return `Default: <installation directory>/${relative}`;
}

function withDefault(out, node) {
    if (undefined === node.default) {
        return out;
    }

    if (underInstallRoot(node.default)) {
        out.$comment = installDerived(node.default);
        return out;
    }

    out.default = node.default;
    return out;
}

//
//  Only ever emit "additionalProperties": false where the schema claims to
//  know every key. A shape derived from a couple of example entries does not,
//  and saying otherwise would flag correct file areas over "acs" and
//  "hashTags" -- see §0.1 of the plan.
//
function isClosed(node) {
    return true === node.closedKeys;
}

function describedFrom(node) {
    return node.description ? { description: node.description } : {};
}

function scalarSchema(node) {
    const out = describedFrom(node);

    out.type = true === node.nullable ? [node.type, 'null'] : node.type;

    if (node.enum) {
        out.enum = true === node.nullable ? [...node.enum, null] : [...node.enum];
    }

    if (undefined !== node.min) {
        out.minimum = node.min;
    }
    if (undefined !== node.max) {
        out.maximum = node.max;
    }
    return withDefault(out, node);
}

function arraySchema(node) {
    const out = describedFrom(node);
    out.type = true === node.nullable ? ['array', 'null'] : 'array';

    //  An empty or mixed default tells us nothing about the elements, and
    //  guessing is how a validator starts rejecting correct configurations.
    if (node.items && NodeType.Unknown !== node.items.type) {
        out.items = convert(node.items);
    }

    return withDefault(out, node);
}

function openMapSchema(node) {
    const out = describedFrom(node);
    out.type = 'object';

    //
    //  The keys are sysop data -- area tags, network names, node addresses --
    //  so any key is legal and only the values are describable.
    //
    const value = node.value && NodeType.Unknown !== node.value.type
        ? convert(node.value)
        : undefined;

    out.additionalProperties = value || true;

    return out;
}

function objectSchema(node) {
    const out = describedFrom(node);
    out.type = 'object';

    const children = node.children || {};
    const keys = Object.keys(children);

    if (keys.length > 0) {
        out.properties = {};
        keys.forEach(key => {
            out.properties[key] = convert(children[key]);
        });
    }

    if (isClosed(node)) {
        //
        //  A leading underscore marks a block that is not configuration at
        //  all -- "_snips" holding fragments for @reference to point at. The
        //  validator skips those at every level, so the artifact has to as
        //  well or it would reject a documented pattern.
        //
        out.patternProperties = { '^_': true };
        out.additionalProperties = false;
    }

    return out;
}

function convert(node) {
    if (!node) {
        return {};
    }

    if (true === node.openMap) {
        return openMapSchema(node);
    }

    if (NodeType.Object === node.type) {
        const object = objectSchema(node);

        if (true !== node.scalarShorthand) {
            return object;
        }

        //
        //  Some blocks accept a bare scalar as documented shorthand for their
        //  commonest field: a ticAreas entry given as a plain string means
        //  { areaTag: <it> }.
        //
        const out = describedFrom(node);
        delete object.description;
        out.anyOf = [
            object,
            {
                $comment: 'Shorthand: a bare scalar names this block\'s primary field.',
                type: SHORTHAND_TYPES,
            },
        ];
        return out;
    }

    if (NodeType.Array === node.type) {
        return arraySchema(node);
    }

    if (NodeType.Unknown === node.type) {
        //
        //  The default was null, {} or absent, and meta did not supply a type.
        //  Fail open: describe the key's existence and accept any value.
        //
        return describedFrom(node);
    }

    return scalarSchema(node);
}

//
//  |schema| is the node tree from buildSchema(). Returns a plain object ready
//  to be serialised.
//
function toJsonSchema(schema) {
    const body = convert(schema);

    return Object.assign(
        {
            $schema: JSON_SCHEMA_DRAFT,
            $id: SCHEMA_ID,
            title: 'ENiGMA½ BBS configuration',
            $comment: ROOT_COMMENT,
        },
        body
    );
}

//  One serialisation, shared by the generator and the staleness guard, so
//  neither can drift from the other over a trailing newline.
function serialize(jsonSchema) {
    return `${JSON.stringify(jsonSchema, null, 4)}\n`;
}

module.exports = {
    toJsonSchema,
    serialize,
    INSTALL_ROOT,
    JSON_SCHEMA_DRAFT,
    SCHEMA_ID,
};
